version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uniformusic db && uniformusic run --host=0.0.0.0 --port=5000
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    # Healthcheck para verificar se o serviço está funcionando
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:5000/"]
      interval: 30s
      timeout: 5s
      retries: 3

