version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: chalice_rest:${CHALICE_REST_VERSION:-latest}
    restart: always
    env_file:
    - .env
    depends_on:
      redis:
        condition: service_healthy
      rmq:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      CHALICE_REST_HOST: 0.0.0.0
      CHALICE_REST_DB_FILE: /db_data/db.sqlite3
      CHALICE_REST_RABBIT_HOST: chalice_rest-rmq
      CHALICE_REST_REDIS_HOST: chalice_rest-redis
      TESTKAFKA_KAFKA_BOOTSTRAP_SERVERS: '["chalice_rest-kafka:9092"]'
    volumes:
    - chalice_rest-db-data:/db_data/

  migrator:
    image: chalice_rest:${CHALICE_REST_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      CHALICE_REST_DB_FILE: /db_data/db.sqlite3
    volumes:
    - chalice_rest-db-data:/db_data/

  redis:
    image: bitnami/redis:6.2.5
    hostname: "chalice_rest-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

  rmq:
    image: rabbitmq:3.9.16-alpine
    hostname: "chalice_rest-rmq"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    healthcheck:
      test: rabbitmq-diagnostics check_running -q
      interval: 3s
      timeout: 3s
      retries: 50

  zookeeper:
    image: "bitnami/zookeeper:3.7.1"
    hostname: "chalice_rest-zookeeper"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_LOG_LEVEL: "ERROR"
    healthcheck:
      test: zkServer.sh status
      interval: 1s
      timeout: 3s
      retries: 30

  kafka:
    image: "bitnami/kafka:3.2.0"
    hostname: "chalice_rest-kafka"
    environment:
      KAFKA_BROKER_ID: "1"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://chalice_rest-kafka:9092"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "chalice_rest-zookeeper:2181"
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server localhost:9092
      interval: 1s
      timeout: 3s
      retries: 30
    depends_on:
      zookeeper:
        condition: service_healthy



volumes:
  chalice_rest-db-data:
    name: chalice_rest-db-data
